name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: amazon-linux-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'  # Specify the version of Terraform you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # Additional steps like testing or notifications can be added here
